### ISSUE TITLE
purecss 有进展么楼主

### ISSUE THREAD

**Issue by zzzzzhowie** [windedge/taro-tailwind#1]

**Comment by liyatang** [comment]
+1

**Comment by windedge** [comment]
https://github.com/windedge/taro-tailwind#%E4%BD%BF%E7%94%A8purgecss%E7%AE%80%E5%8C%96%E7%94%9F%E6%88%90%E7%9A%84tailwindcss

补充了下readme，自己是采用这种方式处理，也可以尝试把它加到config/index.js里
