### ISSUE TITLE
微信小程序 app.wxss 报错

### ISSUE THREAD

**Issue by protogenesis** [windedge/taro-tailwind#3]
在 WIN10 上面按照流程安装后，会报如下错误：
```
2. 使用PostCSS生成
添加talwindcss依赖:


# 使用npm
npm install --save-dev tailwindcss

# 使用yarn
yarn add --dev tailwindcss
复制默认配置tailwind.config.js和基础类定义tailwind.src.css到项目目录:

cp ./node_modules/taro-tailwind/tailwind.config.js ./tailwind.config.js
cp ./node_modules/taro-tailwind/tailwind.src.css ./src/tailwind.src.css
在postcss.config.js中添加:

module.exports = {
  plugins: [
    // ...
    require('tailwindcss'),
    require('taro-tailwind'),
    // ...
  ]
}
然后使用postcss执行生成css文件:

postcss ./src/tailwind.src.css -o ./src/tailwind.css
在app.jsx中引入样式文件

import './tailwind.css'
```
![image](https://user-images.githubusercontent.com/32860504/111727078-2b28af00-88a5-11eb-887a-d956bef15250.png)

这样直接引用是可以的：
```
import 'taro-tailwind/dist/tailwind.css'
```
请问该怎么解决？

**Comment by windedge** [comment]
Taro的版本是多少？

**Comment by protogenesis** [comment]
👽 Taro v3.1.4
OS: WIN 10

**Comment by windedge** [comment]
![image](https://user-images.githubusercontent.com/27651/111760136-52996f00-88d9-11eb-8096-3f9659e3d244.png)
测试了下，Taro v3.1.4是可以正常引入的，如果只是引入预生成的tailwind.css，那上面的postcss的步骤就不需要了。

**Comment by protogenesis** [comment]
请问如果使用 postcss 的话要怎么办？
我按照步骤指示安装无法成功运行，好像是有一部分 CSS 语法在小程序中不支持，能上传一下成功运行的示例代码吗？
谢谢。

**Comment by windedge** [comment]
报错的原因是项目不支持```tailwindcss``` 2.0，现在已经更新支持2.0，并增加了一个sample项目，可以参考下。
